name = "LatexTables"
uuid = "33562111-8cff-4957-beb7-4d2a52ae425e"
authors = ["sadda <adam@utia.cas.cz> and contributors"]
version = "0.1.0"

[deps]
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
